### ISSUE TITLE
Vue 2.2.* support?

### ISSUE THREAD

**Issue by DCzajkowski** [koumoul-dev/vue-openapi#1]
Has this plugin been tested on Vue 2.2.1? Can't seem to get it working :/

**Comment by nicolas-bonnel** [comment]
Hi,

I just tested with Vue 2.2.1 and 2.2.2 and it works well for me. Can you describe more precisely your problem ?

**Comment by DCzajkowski** [comment]
No worries. It didn't work, but then I saw it is too tightly coupled with the Material extension.
Now trying to make my own interpreter that is not as much opinionated. Thanks 😊
