### ISSUE TITLE
"scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5

### ISSUE THREAD

**Issue by jflaflamme** [koumoul-dev/vue-openapi#6]
I get this error from _vue-openapi/src/RequestForm.vue_
Do you plan to update soon ? (For Vue 2.5)

> (Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "slot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scoped slots.

**Comment by nicolas-bonnel** [comment]
Just tested with vue 2.5.3 and I don't have this error message. Can you provide more informations ?

**Comment by jflaflamme** [comment]
Just re-upgraded and can see the error..

I can also confirm you that if I change slot= to slot-scope= in RequestForm.vue error is gone since Vue 2.5 **slot** is replaced by **slot-scope** as the warning :)

Should I make a PR?

``` warning  in ./node_modules/vue-openapi/src/RequestForm.vue

(Emitted value instead of an instance of Error) the "scope" attribute for scoped slots have been deprecated and replaced by "sl
ot-scope" since 2.5. The new "slot-scope" attribute can also be used on plain elements in addition to <template> to denote scop
ed slots.

 @ ./node_modules/vue-openapi/src/RequestForm.vue 10:23-199
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"ug
lify":true}}],"es2015","stage-2"],"plugins":["transform-object-rest-spread","transform-runtime","transform-async-to-generator",
"lodash","transform-object-assign"],"comments":false}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./node_modu
les/vue-openapi/src/OpenApi.vue
 @ ./node_modules/vue-openapi/src/OpenApi.vue
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"ug
lify":true}}],"es2015","stage-2"],"plugins":["transform-object-rest-spread","transform-runtime","transform-async-to-generator",
"lodash","transform-object-assign"],"comments":false}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources```

**Comment by nicolas-bonnel** [comment]
This is a warning message, the code will still work. slot-scope is new in vue 2.5 and vue-openapi should still work with 2.2 <= Vue.js < 2.5
